version: "3.8"

services:
  bot:
    build: .
    container_name: decibot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./config.json:/app/config.json    
